# See dev/buildchecker/README.md
name: buildchecker
on:
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run:
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest

    # secrets for this workflow are configured in the 'autobuildsherrif' environment.
    # 'autobuildsherrif' was the original name of the 'buildchecker' tool - GitHub does
    # not provide a simple way to do a rename, so we leave it as is for now.
    environment: autobuildsherrif

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with: { go-version: '1.19' }

      - name: Setup environment
        run: env
