name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check and create file
      run: |
        FILE=dev/update-embeddings-list/embedded-repos.md
        if [ ! -f "$FILE" ]; then
          touch $FILE
          echo "No embedded repositories at the moment." > $FILE
        fi

    - name: Move file
      run: mv dev/update-embeddings-list/embedded-repos.md doc/cody/embedded-repos.md

    - name: Run tests
      run: go test ./...

    - name: Build
      run: go build -v .
