name: Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run command
        run: gh pr list --label automerge --label embeddings-list-update --json number | jq -r '.[0].number'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        run: gh pr merge $PR_NUMBER --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
